events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    limit_conn_zone $binary_remote_addr zone=limit_per_ip_conn:10m;
    limit_req_zone  $binary_remote_addr zone=limit_per_ip_req:10m rate=10r/s;

    server {
        listen 80;

        # POS 1: Halaman Antrian
        location = /antrian.html {
            root /usr/share/nginx/html;
            allow all;
        }

        # POS 2: Aplikasi Utama
        location / {
            limit_conn limit_per_ip_conn 20;
            limit_req zone=limit_per_ip_req burst=5 nodelay;

            proxy_pass http://skl_app:3000; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            error_page 503 /antrian.html;
        }
    }
}