events {
    worker_connections 1024;
}

http {
    # Setting zona antrian
    limit_conn_zone $binary_remote_addr zone=limit_per_ip:10m;
    limit_conn_status 503;

    server {
        listen 80;

        location / {
            # BATASAN: Hanya 20 koneksi bersamaan yang diizinkan
            limit_conn limit_per_ip 20;
            limit_req zone=limit_per_ip burst=1 nodelay;

            proxy_pass http://nextjs_app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Jika kena limit, arahkan ke halaman antrian
            error_page 503 = @antrian;
        }

        location @antrian {
            rewrite ^ /antrian.html break;
            root /usr/share/nginx/html;
        }
    }
}